federation_version: =2.6.3
subgraphs:
  travelers:
    routing_url: http://travelers:4001/graphql
    schema:
      file: ../travelers/schema.graphql
  locations:
    routing_url: http://locations:4002/graphql
    schema:
      file: ../locations/schema.graphql